[package]
name = "pdf2image"
version = "0.1.0"
authors = ["Sebastian K <s3bk@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf.workspace = true
pdf_render = {path = "../../render" }
pdf_render_vello = { path = "../../vello" }
argh = "*"
pathfinder_geometry.workspace = true
env_logger = "*"
