[package]
name = "pdf_render"
version = "0.1.0"
authors = ["Sebastian Köln <s3bk@protonmail.com>"]
edition = "2021"

[features]
unstable = []
glyphmatcher = ["dep:glyphmatcher"]

[[bench]]
name = "render"
harness = false


[dependencies]
pathfinder_color.workspace = true
pathfinder_geometry.workspace = true
pathfinder_content.workspace = true
log = "0.4"
pdf_encoding = "0.4"
itertools = "*"
image = "0.24.2"
instant = "*"
custom_debug_derive = "*"
globalcache = { git = "https://github.com/s3bk/cachelib", features = ["sync"] }
istring = { git = "https://github.com/s3bk/istring" }
once_cell = "*"
serde_json = "*"
glyphmatcher = { git = "https://github.com/s3bk/glyphmatcher", optional = true }
font.workspace = true
pdf.workspace = true

[dev-dependencies]
criterion = "0.3"
env_logger = "*"
